### PR TITLE
Feature/feature branch

### PR DESCRIPTION
**Pull request by rammazzoti2000**
This is the request for the code review of the solo project Ruby Enumerables

In this project it was required to rebuilt some of the ruby methods such as #each, #each_with_index, #map etc.

Also in the enumerable.rb file it was added some methods test cases to check the result of each custom method.

### CODE REVIEW

**Comment by pelzolga123** [comment]
## Hi Alex, 
### I am marking this pull request as invalid due to invalid Git Flow
 Git Flow should look like this: production `master` branch + main `development` branch + Pull Requests from feature branches to the `develop` ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/git_flow.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/57421589/))

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by rammazzoti2000** [comment]
@pelzolga123  Sorry I think I used `git flow feature finish feature_branch` by mistake 
I will make a new repository. Thank you for the feedback.

**Comment by pelzolga123** [comment]
> @pelzolga123 Sorry I think I used `git flow feature finish feature_branch` by mistake
> I will make a new repository. Thank you for the feedback.

No need to create new repository. Just create new Pull request from feature/feature_branch to develop.

**Comment by rammazzoti2000** [comment]
@pelzolga123 Thank you once again, just created a new pull request like you said.

**Pull request closed without merging**
