### PR TITLE
Feature/feature branch

### PR DESCRIPTION
**Pull request by rammazzoti2000**
This is the request for the code review of the solo project Ruby Enumerables

In this project it was required to rebuilt some of the ruby methods such as #each, #each_with_index, #map etc.

Also in the enumerable.rb file it was added some methods test cases to check the result of each custom method.

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Great job so far :+1: !
### Here are the methods to fix before this project can be approved:
* my_all?
* [x] When no block or argument is given should return true when none of the collection members are false or nil:
` [1,2,3,4,5].my_all? ` - should return true
* [x] When a class is passed as an argument should return true if all of the collection is a member of such class:
`[1, 2, 3].my_all?(Integer)` - should return true
* [x]  When a Regex is passed as an argument should returns true if all of the collection matches the Regex:
`['dog', 'door', 'rod', 'blade'].my_all?(/d/)` - should return true
* [x] When a pattern other than Regex or a Class is given should return true if all of the collection matches the pattern:
` [1, 1, 1].my_all?(1) ` - should return true

* my_any?
* [x] When no block or argument is given should returns true if at least one of the collection is not false or nil:
`[1, nil, false].my_any?(1)` - should return true
* [x] When a class is passed as an argument should return true if at least one of the collection is a member of such class:
`[1, nil, false].my_any?(Integer)` - should return true
* [x] When a Regex is passed as an argument should return false if none of the collection matches the Regex:
`['dog', 'door', 'rod', 'blade'].my_any?(/z/)` - should return false
* [x] When a pattern other than Regex or a Class is given should return false if none of the collection matches the pattern:
`[1, 2 ,3].my_any?(1)`  - should return true

* my_none? 
* [x] When no block or argument is given should return true only if none of the collection members is true:
`[1, 2 ,3].my_none?`  - should return false
* [x] When a class is passed as an argument should return true if none of the collection is a member of such class:
`[1, 2 ,3].my_none?(String)` - should return true
* [x] When a Regex is passed as an argument should return true only if none of the collection matches the Regex:
`[1,2,3,4,5].my_none?(2)` - should return false
* [x] When a pattern other than Regex or a Class is given should return true only if none of the collection matches the pattern:
`[1, 2, 3].my_none?(4)` - should return true

* my_count 
* [x] Should return the number of items in enum through enumeration:
`[1,2,3].my_count` - should return 3
* [x] Should count the number of items in enum that are equal to item if an argument is given:
`[1,1,1,2,3].my_count(1)` - should return 3
* my_inject
* [x] When a symbol is specified should combine each element of the collection by applying the symbol as a named method:
`[5, 1, 2].my_inject("+")` - should return 8

* [x] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by rammazzoti2000** [comment]
Hello @pelzolga123, thank you for the feedback, very helpful, in fact I initially made the pull-request only for the feedback.
Now the methods passes the test-cases required.

**Review by euqueme — APPROVED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @rammazzoti2000  :handshake: 

### Thank you for doing the changes requested by the previous reviewer, :medal_sports: also claps for using the best readme template, your project looks very professional :clap: :clap: :clap:  your project is good enough to pass :heavy_check_mark: 

I'd like you to put attention to this optional requirement :point_down: 

## OPTIONAL

#### my_map should take a block a proc or both

[OPTIONAL]

- [x] in the specifications of the project in the [Odin project](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks) # 12, you were asked to modify your my_map method to take either a proc or a block. And if both a proc and a block are given, only execute the proc.

The real map doesn't have this feature, but as I mentioned before you were asked to have it so I strongly advise to include it in your project

Given 
`my_proc = Proc.new {|num| num > 10 }`

Result
> puts [18, 22, 5, 6] .my_map(my_proc) {|num| num < 10 }  # true true false false

### That's it! :raised_hands: 

### Please :pray: do the change (or not) :man_technologist:  and merge this branch when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: APPROVED :green_apple:

**Comment by rammazzoti2000** [comment]
@euqueme that was a tricky one, thank you very much for your feedback, I always love them :)
Fixed my_map method and added the given test-case.

**Pull request merged**
